name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]
  # Запуск только при публиковании нового релиза

jobs:
  run_tests:
    # Первую джобу смело можем копипастить из экшена для тестирования
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        # Запускаем тесты
        run: coverage run src/tests.py
      - name: Tests report
        run: coverage report

  build_and_pub:
    # Если тесты были пройдены успешно
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      CONTAINER_IMAGE_LATEST: docker.pkg.github.com/timopheym/actions_ci_example/${{secrets.DOCKER_NAME}}:latest
    steps:
      - name: Login to GitHub Packages
        # Сначала мы логинимся в github packages
        run: docker login -u $LOGIN -p $TOKEN docker.pkg.github.com
        # Чекаутим код
      - uses: actions/checkout@master
      - name: Build image
        # Собираем image
        run: docker build -t $CONTAINER_IMAGE_LATEST .
      - name: Push image 
        # Пушим образ в registry
        run: docker push $CONTAINER_IMAGE_LATEST